import { requireAdminAal2 } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { callRpc } from "@/lib/supabase/rpc";
import { Notice } from "@/components/ui/Notice";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { ConfirmSubmitButton } from "@/components/ui/ConfirmSubmitButton";
import { changeUserActiveAction, changeUserRoleAction, inviteUserAction, reviewRoleRequestAction } from "./actions";
import type { AppRole, RoleRequest, UserProfile } from "@/types/app";

export const metadata = { title: "Users and role requests" }; export const dynamic = "force-dynamic";
const roleLabels: Record<AppRole, string> = { administrator: "Administrator", usher: "Usher", pastor: "Pastor", auditor: "Read-only leader" };

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const current = await requireAdminAal2(); const params = await searchParams; const supabase = await createClient(); const admin = createAdminClient();
  const [{ data }, authUsers, requestsResult] = await Promise.all([
    supabase.from("user_profiles").select("id, organization_id, display_name, role, requested_role, role_status, active, created_at, updated_at").order("display_name"),
    admin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
    callRpc<RoleRequest[]>(supabase, "list_staff_role_requests")
  ]);
  const users = (data ?? []) as UserProfile[]; const requests = requestsResult.data ?? []; const emailById = new Map((authUsers.data?.users ?? []).map((user) => [user.id, user.email ?? "Email unavailable"]));
  return <><header className="page-header"><div><h1>Users and role requests</h1><p>Invite staff, approve selected roles, and maintain each person&apos;s individual account.</p></div></header><Notice message={params.notice} kind="success" /><Notice message={params.error} kind="error" />
  <section className="card" style={{ marginBottom: 18 }}><div className="page-header"><div><h2>Pending role requests</h2><p>Pastor and Administrator self-registration requests require your approval.</p></div><span className="badge badge-warning">{requests.length} pending</span></div>{requests.length === 0 ? <div className="empty">No role requests are waiting.</div> : <div className="stack">{requests.map((request) => <article className="card role-request" key={request.user_id}><div><h3>{request.display_name}</h3><p className="muted">{request.email ?? "Email unavailable"} · Requested {request.requested_role}</p>{request.requested_role === "pastor" ? <p className="small"><strong>Church:</strong> {request.church_name ?? "Not supplied"}<br /><strong>Pastor:</strong> {request.pastor_name ?? "Not supplied"}<br /><strong>District:</strong> {request.district ?? "Not supplied"}<br /><strong>Denomination:</strong> {request.denomination ?? "Not supplied"}<br /><strong>Phone:</strong> {request.church_phone ?? "Not supplied"}</p> : <p className="small">Administrator requests receive access to every section and should be verified carefully.</p>}</div><form action={reviewRoleRequestAction} className="role-review-form"><input type="hidden" name="userId" value={request.user_id} /><div className="field"><label htmlFor={`notes-${request.user_id}`}>Review notes</label><textarea id={`notes-${request.user_id}`} name="notes" maxLength={1000} rows={3} /></div><div className="actions"><button className="button button-primary" name="decision" value="approve" type="submit">Approve {request.requested_role}</button><button className="button button-danger" name="decision" value="reject" type="submit">Reject</button></div></form></article>)}</div>}</section>
  <div className="grid grid-2"><section className="card"><h2>Invite staff member</h2><form action={inviteUserAction}><div className="field"><label htmlFor="displayName">Display name</label><input id="displayName" name="displayName" minLength={2} maxLength={80} required /></div><div className="field"><label htmlFor="email">Staff email</label><input id="email" name="email" type="email" maxLength={254} required /></div><div className="field"><label htmlFor="role">Role</label><select id="role" name="role" defaultValue="usher"><option value="usher">Usher</option><option value="pastor">Pastor</option><option value="auditor">Read-only leader</option><option value="administrator">Administrator</option></select></div><SubmitButton className="button button-primary button-full" pendingLabel="Sending invitation…">Invite staff member</SubmitButton></form></section><section className="card"><h2>Permission summary</h2><p><strong>Administrator:</strong> every application section, user approvals, audit, settings, imports, reports, visitors, members, care, and attendance.</p><p><strong>Pastor:</strong> visitors, attendance, members, member imports, care notes, visits, and reports.</p><p><strong>Usher:</strong> visitors, attendance, visitor support notes, and visitor visits.</p><p><strong>Read-only leader:</strong> approved aggregate dashboards and reports.</p></section></div>
  <section className="card" style={{ marginTop: 18 }}><h2>Staff accounts</h2><div className="table-wrap"><table><thead><tr><th>Staff account</th><th>Role</th><th>Approval</th><th>Status</th><th>Role action</th><th>Account action</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.display_name}</strong><br /><small className="muted">{emailById.get(user.id) ?? "Email unavailable"}</small></td><td>{roleLabels[user.role]}</td><td><span className={`badge ${user.role_status === "approved" ? "badge-success" : "badge-warning"}`}>{user.role_status}</span></td><td><span className={`badge ${user.active ? "badge-success" : "badge-danger"}`}>{user.active ? "Active" : "Disabled"}</span></td><td><form action={changeUserRoleAction} className="actions"><input type="hidden" name="userId" value={user.id} /><select name="role" defaultValue={user.role} disabled={user.id === current.id}><option value="administrator">Administrator</option><option value="pastor">Pastor</option><option value="usher">Usher</option><option value="auditor">Read-only leader</option></select><SubmitButton className="button button-secondary button-small" pendingLabel="Saving…">Save role</SubmitButton></form></td><td><form action={changeUserActiveAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="active" value={user.active ? "false" : "true"} />{user.active ? <ConfirmSubmitButton className="button button-secondary button-small" pendingLabel="Saving…" confirmation={`Disable ${user.display_name}?`}>Disable</ConfirmSubmitButton> : <SubmitButton className="button button-secondary button-small" pendingLabel="Saving…">Enable</SubmitButton>}</form></td></tr>)}</tbody></table></div></section></>;
}
